# Generated by Django 4.2.27 on 2026-01-13 03:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApexUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text="User's email address", max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text="User's phone number with country code", max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('full_name', models.CharField(blank=True, help_text="User's full name", max_length=255)),
                ('profile_picture', models.ImageField(blank=True, help_text='Face-validated profile picture', null=True, upload_to='profile_pics/')),
                ('face_validated', models.BooleanField(default=False, help_text='Whether the profile picture has passed face validation')),
                ('google_id', models.CharField(blank=True, help_text='Google OAuth ID', max_length=255, null=True, unique=True)),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('google', 'Google')], default='email', help_text='Primary authentication provider', max_length=50)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user has verified their email/phone')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether email is verified')),
                ('phone_verified', models.BooleanField(default=False, help_text='Whether phone is verified')),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Whether user has completed onboarding (including face validation)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('focus_points', models.PositiveIntegerField(default=0)),
                ('total_focus_time_minutes', models.PositiveIntegerField(default=0)),
                ('courses_completed', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Apex User',
                'verbose_name_plural': 'Apex Users',
                'db_table': 'apex_users',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('email', 'Email Verification'), ('phone', 'Phone Verification'), ('password_reset', 'Password Reset')], max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apex_otp_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_method', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Login histories',
                'db_table': 'apex_login_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
