# Generated by Django 4.2.27 on 2026-01-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apexuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about the user', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='apexuser',
            name='branch',
            field=models.CharField(blank=True, help_text="User's branch/department of study", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apexuser',
            name='college',
            field=models.CharField(blank=True, help_text="User's college/university name", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apexuser',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text="User's learning interests as a list"),
        ),
    ]
