# Generated by Django 4.2.27 on 2026-01-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='apexuser',
            name='display_picture',
            field=models.ImageField(blank=True, help_text="User's display picture for their profile", null=True, upload_to='display_pics/'),
        ),
        migrations.AlterField(
            model_name='apexuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Face-validated profile picture for verification', null=True, upload_to='profile_pics/'),
        ),
    ]
