# Generated by Django 4.2.27 on 2026-02-06 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apexuser_display_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apexuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number with country code", max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must include country code, e.g. '+919876543210'. 10-15 digits after '+'.", regex='^\\+\\d{10,15}$')]),
        ),
    ]
