"""
Management command to populate the database with real courses from various platforms.
Run with: python manage.py populate_courses
"""

from django.core.management.base import BaseCommand
from learning.models import Course
from decimal import Decimal


class Command(BaseCommand):
    help = 'Populate database with real courses from various learning platforms'

    def handle(self, *args, **options):
        courses_data = [
            # ============================================
            # UDEMY COURSES
            # ============================================
            {
                'title': 'The Complete Web Developer Course 3.0',
                'description': 'Learn Web Development by building 25 websites and mobile apps using HTML, CSS, Javascript, PHP, Python, MySQL & more! This comprehensive course takes you from absolute beginner to professional web developer.',
                'instructor': 'Rob Percival',
                'price': Decimal('84.99'),
                'category': 'web_development',
                'difficulty': 'beginner',
                'platform': 'udemy',
                'external_url': 'https://www.udemy.com/course/the-complete-web-developer-course-2/',
                'tags': 'html, css, javascript, php, python, mysql, web development, full stack',
                'duration_hours': 30,
                'total_enrollments': 850000,
                'average_rating': Decimal('4.5'),
                'what_you_learn': 'Build websites with HTML & CSS, Create dynamic pages with PHP & MySQL, Learn Python & build apps, Master JavaScript fundamentals, Deploy websites to the web',
                'prerequisites': 'No programming experience needed. Just a computer with internet access.',
                'syllabus': '1. HTML Fundamentals\n2. CSS Styling & Layouts\n3. JavaScript Basics\n4. jQuery & DOM Manipulation\n5. Bootstrap Framework\n6. PHP Fundamentals\n7. MySQL Databases\n8. Python Introduction\n9. Building Real Projects\n10. Deployment & Hosting',
            },
            {
                'title': 'Machine Learning A-Z: AI, Python & R + ChatGPT Prize [2024]',
                'description': 'Learn to create Machine Learning Algorithms in Python and R from two Data Science experts. We will walk you through step-by-step into the World of Machine Learning. Includes ChatGPT bonus content.',
                'instructor': 'Kirill Eremenko, Hadelin de Ponteves',
                'price': Decimal('94.99'),
                'category': 'machine_learning',
                'difficulty': 'intermediate',
                'platform': 'udemy',
                'external_url': 'https://www.udemy.com/course/machinelearning/',
                'tags': 'machine learning, python, r, data science, regression, classification, clustering, deep learning',
                'duration_hours': 44,
                'total_enrollments': 1000000,
                'average_rating': Decimal('4.5'),
                'what_you_learn': 'Master Machine Learning on Python & R, Make accurate predictions, Build robust Machine Learning models, Use ML for business, Handle advanced techniques like Dimensionality Reduction',
                'prerequisites': 'Basic Python or R knowledge recommended but not required',
                'syllabus': '1. Data Preprocessing\n2. Regression Models\n3. Classification Models\n4. Clustering\n5. Association Rule Learning\n6. Reinforcement Learning\n7. Natural Language Processing\n8. Deep Learning\n9. Dimensionality Reduction\n10. Model Selection & Boosting',
            },
            {
                'title': 'The Complete JavaScript Course 2024: From Zero to Expert!',
                'description': 'The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory. Many courses in one! Build real-world projects and learn the most in-demand JavaScript features.',
                'instructor': 'Jonas Schmedtmann',
                'price': Decimal('89.99'),
                'category': 'web_development',
                'difficulty': 'beginner',
                'platform': 'udemy',
                'external_url': 'https://www.udemy.com/course/the-complete-javascript-course/',
                'tags': 'javascript, es6, npm, nodejs, oop, functional programming, web development',
                'duration_hours': 69,
                'total_enrollments': 750000,
                'average_rating': Decimal('4.7'),
                'what_you_learn': 'JavaScript from scratch to advanced, Modern ES6+ features, How JavaScript works behind the scenes, DOM manipulation, Async JavaScript (Promises, Async/Await), Build 6+ real projects',
                'prerequisites': 'No coding experience necessary - basics of HTML and CSS are helpful but not required',
                'syllabus': '1. JavaScript Fundamentals\n2. Developer Skills & Editor Setup\n3. DOM Manipulation\n4. How JavaScript Works\n5. Data Structures & Operators\n6. Functions\n7. Arrays\n8. OOP with JavaScript\n9. Async JavaScript\n10. Modern JavaScript Development',
            },
            {
                'title': '100 Days of Code: The Complete Python Pro Bootcamp',
                'description': 'Master Python by building 100 projects in 100 days. Learn data science, automation, build websites, games and apps! Become a professional Python programmer.',
                'instructor': 'Dr. Angela Yu',
                'price': Decimal('84.99'),
                'category': 'programming_languages',
                'difficulty': 'beginner',
                'platform': 'udemy',
                'external_url': 'https://www.udemy.com/course/100-days-of-code/',
                'tags': 'python, data science, web development, automation, flask, pandas, selenium',
                'duration_hours': 60,
                'total_enrollments': 1200000,
                'average_rating': Decimal('4.7'),
                'what_you_learn': 'Master Python programming, Build 100 Python projects, Learn automation with Selenium, Create websites with Flask, Work with APIs and web scraping, Data science with Pandas',
                'prerequisites': 'No programming experience needed. A computer with internet access.',
                'syllabus': '1. Python Basics & Variables\n2. Control Flow & Loops\n3. Functions & Recursion\n4. File I/O & Error Handling\n5. OOP Concepts\n6. GUI with Tkinter\n7. APIs & Web Requests\n8. Web Scraping\n9. Flask Web Development\n10. Data Science & Pandas',
            },
            
            # ============================================
            # YOUTUBE PLAYLISTS
            # ============================================
            {
                'title': 'CS50: Introduction to Computer Science',
                'description': 'Harvard University\'s legendary introduction to computer science and the art of programming. Learn computational thinking, problem solving, data structures, algorithms, and web development. This course is the largest open learning course at Harvard with millions of learners worldwide.',
                'instructor': 'David J. Malan (Harvard)',
                'price': Decimal('0.00'),
                'category': 'programming_languages',
                'difficulty': 'beginner',
                'platform': 'youtube',
                'external_url': 'https://www.youtube.com/playlist?list=PLhQjrBD2T380F_inVRXMIHCqLaNUd7bN4',
                'tags': 'computer science, c, python, sql, html, css, javascript, algorithms, data structures, harvard',
                'duration_hours': 25,
                'total_enrollments': 5000000,
                'average_rating': Decimal('4.9'),
                'what_you_learn': 'Computational thinking, Problem solving, Abstraction, Algorithms, Data structures, Memory management, Software engineering, Web development',
                'prerequisites': 'None - this is a true beginner course',
                'syllabus': '1. Scratch & Computational Thinking\n2. C Programming\n3. Arrays\n4. Algorithms\n5. Memory\n6. Data Structures\n7. Python\n8. SQL\n9. HTML, CSS, JavaScript\n10. Flask\n11. Cybersecurity',
            },
            {
                'title': 'Full Stack Web Development Course',
                'description': 'Complete Full Stack Web Development course covering HTML, CSS, JavaScript, React, Node.js, Express, MongoDB, and deployment. Build real-world projects from scratch.',
                'instructor': 'Traversy Media',
                'price': Decimal('0.00'),
                'category': 'web_development',
                'difficulty': 'beginner',
                'platform': 'youtube',
                'external_url': 'https://www.youtube.com/c/TraversyMedia/playlists',
                'tags': 'html, css, javascript, react, nodejs, express, mongodb, mern stack, web development',
                'duration_hours': 40,
                'total_enrollments': 2000000,
                'average_rating': Decimal('4.8'),
                'what_you_learn': 'HTML5 & CSS3, JavaScript ES6+, React.js, Node.js & Express, MongoDB, RESTful APIs, Authentication, Deployment',
                'prerequisites': 'Basic computer skills',
                'syllabus': '1. HTML Crash Course\n2. CSS Fundamentals\n3. JavaScript Basics\n4. Modern JS (ES6+)\n5. React Front To Back\n6. Node.js Crash Course\n7. Express Framework\n8. MongoDB & Mongoose\n9. MERN Stack Project\n10. Deployment',
            },
            {
                'title': 'Python Full Course for Beginners',
                'description': 'Learn Python programming from scratch. This comprehensive course covers everything from basic syntax to advanced concepts like OOP, file handling, and working with libraries.',
                'instructor': 'Programming with Mosh',
                'price': Decimal('0.00'),
                'category': 'programming_languages',
                'difficulty': 'beginner',
                'platform': 'youtube',
                'external_url': 'https://www.youtube.com/watch?v=_uQrJ0TkZlc',
                'tags': 'python, programming, automation, beginner, oop, machine learning prep',
                'duration_hours': 6,
                'total_enrollments': 30000000,
                'average_rating': Decimal('4.9'),
                'what_you_learn': 'Python syntax, Variables and data types, Control flow, Functions, OOP, File handling, Error handling, Modules and packages',
                'prerequisites': 'No prior programming experience required',
                'syllabus': '1. Introduction & Setup\n2. Variables & Data Types\n3. Operators\n4. Control Flow\n5. Loops\n6. Functions\n7. Data Structures\n8. Classes & OOP\n9. Modules\n10. File Handling',
            },
            {
                'title': 'React Tutorial for Beginners',
                'description': 'Learn React from the ground up - all the way from basic concepts to advanced techniques used in real-world applications. Build multiple projects including a task manager and e-commerce app.',
                'instructor': 'Net Ninja',
                'price': Decimal('0.00'),
                'category': 'web_development',
                'difficulty': 'intermediate',
                'platform': 'youtube',
                'external_url': 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9gZD-Tvwfod2gaISzfRiP9d',
                'tags': 'react, javascript, frontend, components, hooks, state management, web development',
                'duration_hours': 8,
                'total_enrollments': 1500000,
                'average_rating': Decimal('4.8'),
                'what_you_learn': 'React Components, JSX, Props & State, React Hooks, Context API, React Router, Forms & Validation, Building real apps',
                'prerequisites': 'Basic JavaScript knowledge',
                'syllabus': '1. React Basics\n2. Components & Templates\n3. Click Events\n4. useState Hook\n5. Lists & Keys\n6. Props\n7. useEffect Hook\n8. Conditional Templates\n9. Forms\n10. React Router',
            },
            
            # ============================================
            # COURSERA
            # ============================================
            {
                'title': 'Deep Learning Specialization',
                'description': 'Master Deep Learning and break into AI. Build neural networks and lead successful machine learning projects. Learn from Andrew Ng, the pioneer of online learning and AI.',
                'instructor': 'Andrew Ng (DeepLearning.AI)',
                'price': Decimal('49.00'),
                'category': 'artificial_intelligence',
                'difficulty': 'intermediate',
                'platform': 'coursera',
                'external_url': 'https://www.coursera.org/specializations/deep-learning',
                'tags': 'deep learning, neural networks, tensorflow, cnn, rnn, nlp, computer vision',
                'duration_hours': 120,
                'total_enrollments': 800000,
                'average_rating': Decimal('4.9'),
                'what_you_learn': 'Build and train deep neural networks, Implement CNNs for computer vision, RNNs for sequence data, Transformers, LSTM, Attention models, Apply ML to healthcare, autonomous driving, NLP',
                'prerequisites': 'Basic Python, Linear Algebra, Calculus',
                'syllabus': '1. Neural Networks and Deep Learning\n2. Improving Deep Neural Networks\n3. Structuring ML Projects\n4. Convolutional Neural Networks\n5. Sequence Models',
            },
            {
                'title': 'Google Data Analytics Professional Certificate',
                'description': 'Start your career in data analytics. Learn in-demand skills like data cleaning, analysis, and visualization. Get job-ready with hands-on projects and earn a certificate from Google.',
                'instructor': 'Google',
                'price': Decimal('39.00'),
                'category': 'data_science',
                'difficulty': 'beginner',
                'platform': 'coursera',
                'external_url': 'https://www.coursera.org/professional-certificates/google-data-analytics',
                'tags': 'data analytics, sql, r, tableau, spreadsheets, data visualization, google',
                'duration_hours': 180,
                'total_enrollments': 1500000,
                'average_rating': Decimal('4.8'),
                'what_you_learn': 'Data cleaning and organization, Data analysis with SQL and R, Data visualization with Tableau, Analytical thinking, Portfolio projects',
                'prerequisites': 'No experience required',
                'syllabus': '1. Foundations: Data Everywhere\n2. Ask Questions to Make Decisions\n3. Prepare Data for Exploration\n4. Process Data from Dirty to Clean\n5. Analyze Data to Answer Questions\n6. Share Data Through Visualization\n7. Data Analysis with R\n8. Google Data Analytics Capstone',
            },
            {
                'title': 'IBM Full Stack Software Developer',
                'description': 'Prepare for a career as a full stack developer. Build your skills in front-end and back-end development with hands-on projects using industry tools.',
                'instructor': 'IBM',
                'price': Decimal('39.00'),
                'category': 'web_development',
                'difficulty': 'beginner',
                'platform': 'coursera',
                'external_url': 'https://www.coursera.org/professional-certificates/ibm-full-stack-cloud-developer',
                'tags': 'full stack, cloud, python, django, nodejs, react, devops, containers, kubernetes',
                'duration_hours': 200,
                'total_enrollments': 500000,
                'average_rating': Decimal('4.6'),
                'what_you_learn': 'Full stack web development, Cloud application development, Python and Django, Node.js and React, Containers and Kubernetes, DevOps practices',
                'prerequisites': 'No prior experience required',
                'syllabus': '1. Introduction to Cloud Computing\n2. HTML, CSS, JavaScript\n3. Python for Data Science\n4. Developing Applications with Python\n5. Containers & Kubernetes\n6. Python Project for AI\n7. Node.js & Express\n8. React\n9. Full Stack Cloud Development\n10. DevOps Capstone',
            },
            
            # ============================================
            # INFOSYS SPRINGBOARD
            # ============================================
            {
                'title': 'Python for Beginners',
                'description': 'Learn Python programming fundamentals with Infosys Springboard. This course covers basic to intermediate Python concepts with hands-on exercises and real-world examples.',
                'instructor': 'Infosys Springboard',
                'price': Decimal('0.00'),
                'category': 'programming_languages',
                'difficulty': 'beginner',
                'platform': 'infosys',
                'external_url': 'https://infyspringboard.onwingspan.com/',
                'tags': 'python, programming, infosys, certification, beginner',
                'duration_hours': 20,
                'total_enrollments': 200000,
                'average_rating': Decimal('4.5'),
                'what_you_learn': 'Python syntax and semantics, Data types and structures, Control flow, Functions, File handling, Introduction to OOP',
                'prerequisites': 'No prior programming experience',
                'syllabus': '1. Introduction to Python\n2. Variables & Data Types\n3. Operators & Expressions\n4. Control Structures\n5. Functions\n6. Lists & Tuples\n7. Dictionaries & Sets\n8. File Operations\n9. Exception Handling\n10. OOP Basics',
            },
            {
                'title': 'Data Science Foundation',
                'description': 'Build a strong foundation in Data Science with this comprehensive course. Learn statistics, Python for data analysis, and machine learning basics.',
                'instructor': 'Infosys Springboard',
                'price': Decimal('0.00'),
                'category': 'data_science',
                'difficulty': 'intermediate',
                'platform': 'infosys',
                'external_url': 'https://infyspringboard.onwingspan.com/',
                'tags': 'data science, statistics, python, machine learning, analytics, infosys',
                'duration_hours': 40,
                'total_enrollments': 150000,
                'average_rating': Decimal('4.4'),
                'what_you_learn': 'Statistical analysis, Python for data science, Data visualization, Machine learning fundamentals, Business analytics',
                'prerequisites': 'Basic Python knowledge',
                'syllabus': '1. Introduction to Data Science\n2. Statistics Fundamentals\n3. Python for Data Analysis\n4. NumPy & Pandas\n5. Data Visualization\n6. Exploratory Data Analysis\n7. Machine Learning Basics\n8. Supervised Learning\n9. Unsupervised Learning\n10. Project Work',
            },
            {
                'title': 'Cloud Computing Fundamentals',
                'description': 'Understand cloud computing concepts, services, and deployment models. Learn about AWS, Azure, and Google Cloud Platform basics.',
                'instructor': 'Infosys Springboard',
                'price': Decimal('0.00'),
                'category': 'cloud_computing',
                'difficulty': 'beginner',
                'platform': 'infosys',
                'external_url': 'https://infyspringboard.onwingspan.com/',
                'tags': 'cloud computing, aws, azure, gcp, iaas, paas, saas',
                'duration_hours': 25,
                'total_enrollments': 100000,
                'average_rating': Decimal('4.3'),
                'what_you_learn': 'Cloud computing concepts, IaaS, PaaS, SaaS models, AWS basics, Azure fundamentals, GCP introduction, Cloud security',
                'prerequisites': 'Basic IT knowledge',
                'syllabus': '1. Introduction to Cloud\n2. Cloud Service Models\n3. Cloud Deployment Models\n4. AWS Fundamentals\n5. Azure Basics\n6. GCP Overview\n7. Cloud Storage\n8. Cloud Networking\n9. Cloud Security\n10. Cloud Best Practices',
            },
            
            # ============================================
            # NPTEL (IIT Courses)
            # ============================================
            {
                'title': 'Programming, Data Structures and Algorithms Using Python',
                'description': 'This course is an introduction to programming and problem solving in Python. It covers basic programming concepts, data structures, and algorithms. Taught by IIT Madras professors.',
                'instructor': 'Prof. Madhavan Mukund (IIT Madras)',
                'price': Decimal('0.00'),
                'category': 'programming_languages',
                'difficulty': 'intermediate',
                'platform': 'nptel',
                'external_url': 'https://nptel.ac.in/courses/106106145',
                'tags': 'python, data structures, algorithms, programming, iit, nptel',
                'duration_hours': 40,
                'total_enrollments': 300000,
                'average_rating': Decimal('4.7'),
                'what_you_learn': 'Python programming, Algorithmic thinking, Data structures, Complexity analysis, Sorting and searching, Graph algorithms',
                'prerequisites': 'Basic mathematics',
                'syllabus': '1. Python Basics\n2. Lists & Dictionaries\n3. Sorting Algorithms\n4. Searching Algorithms\n5. Algorithm Analysis\n6. Stacks & Queues\n7. Trees & Graphs\n8. Dynamic Programming\n9. Greedy Algorithms\n10. Final Project',
            },
            {
                'title': 'Deep Learning',
                'description': 'Comprehensive course on deep learning covering neural networks, CNNs, RNNs, and advanced architectures. Includes mathematical foundations and practical implementations.',
                'instructor': 'Prof. Mitesh M. Khapra (IIT Madras)',
                'price': Decimal('0.00'),
                'category': 'artificial_intelligence',
                'difficulty': 'advanced',
                'platform': 'nptel',
                'external_url': 'https://nptel.ac.in/courses/106106184',
                'tags': 'deep learning, neural networks, cnn, rnn, nlp, computer vision, iit',
                'duration_hours': 60,
                'total_enrollments': 250000,
                'average_rating': Decimal('4.8'),
                'what_you_learn': 'Neural network fundamentals, Backpropagation, CNNs, RNNs, LSTMs, Transformers, Attention mechanisms, GANs',
                'prerequisites': 'Linear algebra, Calculus, Basic ML',
                'syllabus': '1. Introduction to Deep Learning\n2. Perceptrons & Neurons\n3. Feedforward Networks\n4. Backpropagation\n5. Optimization\n6. CNNs\n7. RNNs & LSTMs\n8. Attention & Transformers\n9. GANs\n10. Advanced Topics',
            },
            {
                'title': 'Database Management System',
                'description': 'Learn database concepts, SQL, normalization, transactions, and database design. Comprehensive coverage of relational database management systems.',
                'instructor': 'Prof. Partha Pratim Das (IIT Kharagpur)',
                'price': Decimal('0.00'),
                'category': 'database',
                'difficulty': 'intermediate',
                'platform': 'nptel',
                'external_url': 'https://nptel.ac.in/courses/106105175',
                'tags': 'database, sql, dbms, normalization, transactions, iit',
                'duration_hours': 40,
                'total_enrollments': 200000,
                'average_rating': Decimal('4.6'),
                'what_you_learn': 'Relational model, SQL queries, Normalization, Transaction management, Indexing, Query optimization',
                'prerequisites': 'Basic programming knowledge',
                'syllabus': '1. Introduction to DBMS\n2. ER Modeling\n3. Relational Model\n4. SQL Basics\n5. Advanced SQL\n6. Normalization\n7. Transactions\n8. Indexing\n9. Query Processing\n10. NoSQL Introduction',
            },
            
            # ============================================
            # CISCO NETWORKING ACADEMY
            # ============================================
            {
                'title': 'CCNA: Introduction to Networks',
                'description': 'Start your networking journey with Cisco. Learn networking fundamentals, IP addressing, and basic router and switch configurations. Industry-recognized certification path.',
                'instructor': 'Cisco Networking Academy',
                'price': Decimal('0.00'),
                'category': 'networking',
                'difficulty': 'beginner',
                'platform': 'cisco',
                'external_url': 'https://www.netacad.com/courses/networking/ccna-introduction-networks',
                'tags': 'networking, cisco, ccna, ip addressing, routing, switching',
                'duration_hours': 70,
                'total_enrollments': 500000,
                'average_rating': Decimal('4.7'),
                'what_you_learn': 'Network fundamentals, IP addressing, Subnetting, Router configuration, Switch configuration, Network security basics',
                'prerequisites': 'Basic computer skills',
                'syllabus': '1. Networking Today\n2. Basic Switch and End Device Configuration\n3. Protocols and Models\n4. Physical Layer\n5. Data Link Layer\n6. Network Layer\n7. IP Addressing\n8. Subnetting\n9. Transport Layer\n10. Application Layer',
            },
            {
                'title': 'CyberOps Associate',
                'description': 'Prepare for a career in cybersecurity operations. Learn to detect, analyze, and respond to cybersecurity threats in a Security Operations Center (SOC).',
                'instructor': 'Cisco Networking Academy',
                'price': Decimal('0.00'),
                'category': 'cybersecurity',
                'difficulty': 'intermediate',
                'platform': 'cisco',
                'external_url': 'https://www.netacad.com/courses/cybersecurity/cyberops-associate',
                'tags': 'cybersecurity, soc, security operations, threat analysis, cisco, certification',
                'duration_hours': 70,
                'total_enrollments': 200000,
                'average_rating': Decimal('4.6'),
                'what_you_learn': 'Security concepts, Security monitoring, Host-based analysis, Network intrusion analysis, Security policies',
                'prerequisites': 'Basic networking knowledge',
                'syllabus': '1. The Danger\n2. Fighters in the War\n3. Windows Operating System\n4. Linux Overview\n5. Network Protocols\n6. Ethernet and IP\n7. Connectivity Verification\n8. Address Resolution Protocol\n9. Network Attack Methodology\n10. Attack the Foundation',
            },
            {
                'title': 'Introduction to Cybersecurity',
                'description': 'Explore the world of cybersecurity. Learn about cyber threats, vulnerabilities, and how to protect yourself and organizations from attacks.',
                'instructor': 'Cisco Networking Academy',
                'price': Decimal('0.00'),
                'category': 'cybersecurity',
                'difficulty': 'beginner',
                'platform': 'cisco',
                'external_url': 'https://www.netacad.com/courses/cybersecurity/introduction-cybersecurity',
                'tags': 'cybersecurity, security, cyber threats, malware, social engineering, cisco',
                'duration_hours': 15,
                'total_enrollments': 1000000,
                'average_rating': Decimal('4.8'),
                'what_you_learn': 'Cybersecurity fundamentals, Common threats, Attack types, Security best practices, Career paths in security',
                'prerequisites': 'None',
                'syllabus': '1. The Need for Cybersecurity\n2. Attacks, Concepts and Techniques\n3. Protecting Your Data and Privacy\n4. Protecting the Organization\n5. Cybersecurity Careers',
            },
            
            # ============================================
            # CYFRIN UPDRAFT (Blockchain/Smart Contracts)
            # ============================================
            {
                'title': 'Blockchain Developer Bootcamp',
                'description': 'The most comprehensive blockchain developer course. Learn Solidity, smart contracts, DeFi, and become a certified blockchain developer. Includes real-world projects and security auditing.',
                'instructor': 'Patrick Collins (Cyfrin)',
                'price': Decimal('0.00'),
                'category': 'blockchain',
                'difficulty': 'intermediate',
                'platform': 'cyfrin',
                'external_url': 'https://updraft.cyfrin.io/',
                'tags': 'blockchain, solidity, smart contracts, ethereum, defi, web3, security',
                'duration_hours': 100,
                'total_enrollments': 100000,
                'average_rating': Decimal('4.9'),
                'what_you_learn': 'Solidity programming, Smart contract development, DeFi protocols, Security best practices, Testing and deployment, NFTs and tokens',
                'prerequisites': 'Basic programming knowledge (JavaScript preferred)',
                'syllabus': '1. Blockchain Basics\n2. Solidity Fundamentals\n3. Foundry Development\n4. Smart Contract Testing\n5. Storage & Gas Optimization\n6. Foundry NFTs\n7. DeFi Protocols\n8. Security Basics\n9. Auditing\n10. Advanced Patterns',
            },
            {
                'title': 'Smart Contract Security & Auditing',
                'description': 'Learn to find and fix vulnerabilities in smart contracts. Become a security researcher and auditor. Includes real audit reports and bug bounty preparation.',
                'instructor': 'Patrick Collins (Cyfrin)',
                'price': Decimal('0.00'),
                'category': 'blockchain',
                'difficulty': 'advanced',
                'platform': 'cyfrin',
                'external_url': 'https://updraft.cyfrin.io/courses/security',
                'tags': 'smart contracts, security, auditing, solidity, ethereum, bug bounty',
                'duration_hours': 80,
                'total_enrollments': 50000,
                'average_rating': Decimal('4.9'),
                'what_you_learn': 'Security vulnerabilities, Audit methodologies, Static analysis tools, Fuzzing, Formal verification, Report writing',
                'prerequisites': 'Solidity development experience',
                'syllabus': '1. Security Review Process\n2. Common Vulnerabilities\n3. Reentrancy Attacks\n4. Oracle Manipulation\n5. Static Analysis\n6. Fuzzing\n7. Formal Verification\n8. Audit Reports\n9. Bug Bounties\n10. Advanced Attacks',
            },
            
            # ============================================
            # FREECODECAMP
            # ============================================
            {
                'title': 'Responsive Web Design Certification',
                'description': 'Learn HTML and CSS by building 20 real projects. Earn a free verified certification. Master responsive design, CSS Grid, and Flexbox.',
                'instructor': 'freeCodeCamp',
                'price': Decimal('0.00'),
                'category': 'web_development',
                'difficulty': 'beginner',
                'platform': 'freecodecamp',
                'external_url': 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
                'tags': 'html, css, responsive design, flexbox, grid, web development, certification',
                'duration_hours': 300,
                'total_enrollments': 5000000,
                'average_rating': Decimal('4.8'),
                'what_you_learn': 'HTML5 semantic elements, CSS styling, Flexbox layouts, CSS Grid, Responsive design, Accessibility',
                'prerequisites': 'None',
                'syllabus': '1. Learn HTML by Building a Cat Photo App\n2. Learn Basic CSS\n3. CSS Box Model\n4. CSS Flexbox\n5. Typography\n6. Accessibility\n7. CSS Variables\n8. CSS Grid\n9. Responsive Design\n10. 5 Certification Projects',
            },
            {
                'title': 'JavaScript Algorithms and Data Structures',
                'description': 'Master JavaScript programming and computer science fundamentals. Build algorithms and data structures while earning a verified certification.',
                'instructor': 'freeCodeCamp',
                'price': Decimal('0.00'),
                'category': 'programming_languages',
                'difficulty': 'intermediate',
                'platform': 'freecodecamp',
                'external_url': 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/',
                'tags': 'javascript, algorithms, data structures, es6, oop, functional programming',
                'duration_hours': 300,
                'total_enrollments': 3000000,
                'average_rating': Decimal('4.7'),
                'what_you_learn': 'JavaScript fundamentals, ES6 features, Regular expressions, Debugging, Data structures, Algorithm scripting, OOP, Functional programming',
                'prerequisites': 'Basic HTML/CSS recommended',
                'syllabus': '1. Basic JavaScript\n2. ES6\n3. Regular Expressions\n4. Debugging\n5. Basic Data Structures\n6. Basic Algorithm Scripting\n7. OOP\n8. Functional Programming\n9. Intermediate Algorithm Scripting\n10. Certification Projects',
            },
            {
                'title': 'Scientific Computing with Python',
                'description': 'Learn Python programming and build 5 scientific computing projects. Earn a verified certification from freeCodeCamp.',
                'instructor': 'freeCodeCamp',
                'price': Decimal('0.00'),
                'category': 'programming_languages',
                'difficulty': 'intermediate',
                'platform': 'freecodecamp',
                'external_url': 'https://www.freecodecamp.org/learn/scientific-computing-with-python/',
                'tags': 'python, scientific computing, algorithms, data analysis, certification',
                'duration_hours': 300,
                'total_enrollments': 1000000,
                'average_rating': Decimal('4.6'),
                'what_you_learn': 'Python syntax, Data types, Functions, Classes, File handling, Scientific computing concepts',
                'prerequisites': 'None',
                'syllabus': '1. Python Fundamentals\n2. Control Flow\n3. Functions\n4. Recursion\n5. Data Structures\n6. OOP\n7. Special Methods\n8. Regular Expressions\n9. Lambda Functions\n10. Certification Projects',
            },
            
            # ============================================
            # HACKERRANK
            # ============================================
            {
                'title': 'Python Skills Certification',
                'description': 'Validate your Python programming skills with HackerRank certification. Covers basic to intermediate Python concepts with coding challenges.',
                'instructor': 'HackerRank',
                'price': Decimal('0.00'),
                'category': 'programming_languages',
                'difficulty': 'intermediate',
                'platform': 'hackerrank',
                'external_url': 'https://www.hackerrank.com/skills-verification/python_basic',
                'tags': 'python, certification, coding challenges, practice, skills verification',
                'duration_hours': 10,
                'total_enrollments': 500000,
                'average_rating': Decimal('4.5'),
                'what_you_learn': 'Python syntax, Data types, Control flow, Functions, OOP, Error handling',
                'prerequisites': 'Basic programming knowledge',
                'syllabus': '1. Scalar Types\n2. Operators and Expressions\n3. Classes\n4. Strings\n5. File Handling\n6. Functions\n7. Built-in Functions\n8. Functional Programming\n9. Error Handling\n10. Certification Test',
            },
            {
                'title': 'SQL Skills Certification',
                'description': 'Prove your SQL proficiency with HackerRank certification. Practice with real SQL problems and earn a verified badge.',
                'instructor': 'HackerRank',
                'price': Decimal('0.00'),
                'category': 'database',
                'difficulty': 'intermediate',
                'platform': 'hackerrank',
                'external_url': 'https://www.hackerrank.com/skills-verification/sql_intermediate',
                'tags': 'sql, database, certification, queries, joins, subqueries',
                'duration_hours': 15,
                'total_enrollments': 400000,
                'average_rating': Decimal('4.5'),
                'what_you_learn': 'SQL queries, Joins, Subqueries, Aggregations, Window functions, Query optimization',
                'prerequisites': 'Basic SQL knowledge',
                'syllabus': '1. Basic Select\n2. Advanced Select\n3. Aggregation\n4. Basic Join\n5. Advanced Join\n6. Alternative Queries\n7. Subqueries\n8. Window Functions\n9. Data Manipulation\n10. Certification Test',
            },
            {
                'title': 'Problem Solving (Algorithms) Certification',
                'description': 'Master algorithm design and problem solving. Practice with hundreds of coding challenges and earn HackerRank certification.',
                'instructor': 'HackerRank',
                'price': Decimal('0.00'),
                'category': 'programming_languages',
                'difficulty': 'advanced',
                'platform': 'hackerrank',
                'external_url': 'https://www.hackerrank.com/skills-verification/problem_solving_intermediate',
                'tags': 'algorithms, data structures, problem solving, coding challenges, competitive programming',
                'duration_hours': 50,
                'total_enrollments': 300000,
                'average_rating': Decimal('4.6'),
                'what_you_learn': 'Algorithm design, Time complexity, Space complexity, Dynamic programming, Graph algorithms, Optimization',
                'prerequisites': 'Strong programming foundation',
                'syllabus': '1. Arrays\n2. Strings\n3. Sorting\n4. Searching\n5. Graph Theory\n6. Greedy Algorithms\n7. Dynamic Programming\n8. Recursion\n9. Mathematics\n10. Certification Test',
            },
            
            # ============================================
            # CODECHEF
            # ============================================
            {
                'title': 'Competitive Programming Learning Path',
                'description': 'Master competitive programming with CodeChef. Learn algorithmic problem solving through structured practice and contests.',
                'instructor': 'CodeChef',
                'price': Decimal('0.00'),
                'category': 'programming_languages',
                'difficulty': 'intermediate',
                'platform': 'codechef',
                'external_url': 'https://www.codechef.com/learning',
                'tags': 'competitive programming, algorithms, data structures, contests, problem solving',
                'duration_hours': 100,
                'total_enrollments': 200000,
                'average_rating': Decimal('4.5'),
                'what_you_learn': 'Competitive programming techniques, Algorithm optimization, Contest strategies, Problem solving patterns',
                'prerequisites': 'Basic programming knowledge',
                'syllabus': '1. Getting Started\n2. Basic Algorithms\n3. Number Theory\n4. Sorting Algorithms\n5. Searching Techniques\n6. Graphs\n7. Dynamic Programming\n8. Advanced DS\n9. Contest Practice\n10. Rating Improvement',
            },
            {
                'title': 'Data Structures & Algorithms in C++',
                'description': 'Learn DSA with C++ through CodeChef. Comprehensive coverage of data structures and algorithms with practice problems.',
                'instructor': 'CodeChef',
                'price': Decimal('0.00'),
                'category': 'programming_languages',
                'difficulty': 'intermediate',
                'platform': 'codechef',
                'external_url': 'https://www.codechef.com/certification/data-structures-and-algorithms/prepare',
                'tags': 'c++, data structures, algorithms, competitive programming, certification',
                'duration_hours': 80,
                'total_enrollments': 150000,
                'average_rating': Decimal('4.6'),
                'what_you_learn': 'C++ STL, Arrays and strings, Linked lists, Trees, Graphs, Sorting, Searching, DP',
                'prerequisites': 'Basic C/C++ knowledge',
                'syllabus': '1. C++ Basics & STL\n2. Arrays & Strings\n3. Linked Lists\n4. Stacks & Queues\n5. Trees\n6. Binary Search Trees\n7. Heaps\n8. Graphs\n9. Dynamic Programming\n10. Advanced Problems',
            },
            
            # ============================================
            # ADDITIONAL POPULAR COURSES
            # ============================================
            {
                'title': 'AWS Cloud Practitioner Essentials',
                'description': 'Start your AWS cloud journey. Learn cloud concepts, AWS services, security, and pricing. Prepare for the AWS Certified Cloud Practitioner exam.',
                'instructor': 'AWS Training',
                'price': Decimal('0.00'),
                'category': 'cloud_computing',
                'difficulty': 'beginner',
                'platform': 'coursera',
                'external_url': 'https://www.coursera.org/learn/aws-cloud-practitioner-essentials',
                'tags': 'aws, cloud, certification, ec2, s3, lambda, cloud practitioner',
                'duration_hours': 25,
                'total_enrollments': 400000,
                'average_rating': Decimal('4.7'),
                'what_you_learn': 'AWS Cloud concepts, Core AWS services, Security and compliance, Billing and pricing, Cloud architecture',
                'prerequisites': 'None',
                'syllabus': '1. Introduction to AWS\n2. Compute in the Cloud\n3. Global Infrastructure\n4. Networking\n5. Storage and Databases\n6. Security\n7. Monitoring\n8. Pricing\n9. Migration\n10. Exam Preparation',
            },
            {
                'title': 'Docker & Kubernetes: The Complete Guide',
                'description': 'Master Docker and Kubernetes. Learn containerization, orchestration, and modern DevOps practices through hands-on projects.',
                'instructor': 'Stephen Grider',
                'price': Decimal('84.99'),
                'category': 'devops',
                'difficulty': 'intermediate',
                'platform': 'udemy',
                'external_url': 'https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/',
                'tags': 'docker, kubernetes, containers, devops, deployment, orchestration, ci/cd',
                'duration_hours': 22,
                'total_enrollments': 300000,
                'average_rating': Decimal('4.6'),
                'what_you_learn': 'Docker fundamentals, Container networking, Kubernetes architecture, Deployments, Services, CI/CD pipelines',
                'prerequisites': 'Basic command line experience',
                'syllabus': '1. Docker Basics\n2. Building Custom Images\n3. Docker Compose\n4. Production Workflow\n5. CI/CD\n6. Kubernetes Intro\n7. Kubernetes in Production\n8. HTTPS Setup\n9. Local K8s Development\n10. Skaffold',
            },
            {
                'title': 'React Native - The Practical Guide',
                'description': 'Build native iOS and Android apps with JavaScript and React. Create real-world mobile apps from scratch.',
                'instructor': 'Maximilian Schwarzmüller',
                'price': Decimal('94.99'),
                'category': 'mobile_development',
                'difficulty': 'intermediate',
                'platform': 'udemy',
                'external_url': 'https://www.udemy.com/course/react-native-the-practical-guide/',
                'tags': 'react native, mobile development, ios, android, javascript, cross-platform',
                'duration_hours': 32,
                'total_enrollments': 250000,
                'average_rating': Decimal('4.7'),
                'what_you_learn': 'React Native fundamentals, Navigation, State management, Native device features, Publishing apps',
                'prerequisites': 'JavaScript and React basics',
                'syllabus': '1. Getting Started\n2. React Native Basics\n3. Debugging\n4. Components & Styling\n5. Navigation\n6. State Management\n7. HTTP Requests\n8. Authentication\n9. Native Device Features\n10. Push Notifications',
            },
            {
                'title': 'Flutter & Dart - The Complete Guide',
                'description': 'Build beautiful native mobile apps with Flutter. Learn Dart programming and create iOS and Android apps with one codebase.',
                'instructor': 'Maximilian Schwarzmüller',
                'price': Decimal('94.99'),
                'category': 'mobile_development',
                'difficulty': 'beginner',
                'platform': 'udemy',
                'external_url': 'https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/',
                'tags': 'flutter, dart, mobile development, ios, android, cross-platform',
                'duration_hours': 42,
                'total_enrollments': 350000,
                'average_rating': Decimal('4.6'),
                'what_you_learn': 'Dart programming, Flutter widgets, State management, Navigation, Firebase integration, Publishing',
                'prerequisites': 'Basic programming knowledge',
                'syllabus': '1. Introduction\n2. Dart Basics\n3. Flutter Basics\n4. Running Apps\n5. Widgets Deep Dive\n6. Responsive & Adaptive\n7. Navigation\n8. State Management\n9. User Input & Forms\n10. HTTP & Firebase',
            },
            {
                'title': 'Ethical Hacking - The Complete Course',
                'description': 'Learn ethical hacking from scratch. Master penetration testing, network security, and web application security.',
                'instructor': 'Zaid Sabih',
                'price': Decimal('84.99'),
                'category': 'cybersecurity',
                'difficulty': 'intermediate',
                'platform': 'udemy',
                'external_url': 'https://www.udemy.com/course/learn-ethical-hacking-from-scratch/',
                'tags': 'ethical hacking, penetration testing, cybersecurity, kali linux, network security',
                'duration_hours': 25,
                'total_enrollments': 600000,
                'average_rating': Decimal('4.6'),
                'what_you_learn': 'Network penetration testing, Web application hacking, Wireless security, Social engineering, Post exploitation',
                'prerequisites': 'Basic IT knowledge',
                'syllabus': '1. Lab Setup\n2. Linux Basics\n3. Network Hacking\n4. Gaining Access\n5. Post Exploitation\n6. Website Hacking\n7. SQL Injection\n8. XSS Attacks\n9. Social Engineering\n10. Creating Reports',
            },
            {
                'title': 'Git & GitHub Crash Course',
                'description': 'Master Git version control and GitHub. Learn branching, merging, pull requests, and collaboration workflows.',
                'instructor': 'Traversy Media',
                'price': Decimal('0.00'),
                'category': 'software_engineering',
                'difficulty': 'beginner',
                'platform': 'youtube',
                'external_url': 'https://www.youtube.com/watch?v=SWYqp7iY_Tc',
                'tags': 'git, github, version control, branching, collaboration, devops',
                'duration_hours': 2,
                'total_enrollments': 2500000,
                'average_rating': Decimal('4.9'),
                'what_you_learn': 'Git basics, Branching and merging, Remote repositories, GitHub workflows, Pull requests, Collaboration',
                'prerequisites': 'None',
                'syllabus': '1. What is Git?\n2. Installation\n3. Basic Commands\n4. Branching\n5. Merging\n6. GitHub Setup\n7. Push & Pull\n8. Pull Requests\n9. Collaboration\n10. Best Practices',
            },
            {
                'title': 'System Design Interview Prep',
                'description': 'Prepare for system design interviews. Learn to design scalable systems like those at Google, Facebook, and Amazon.',
                'instructor': 'Tech Dummies Narendra L',
                'price': Decimal('0.00'),
                'category': 'software_engineering',
                'difficulty': 'advanced',
                'platform': 'youtube',
                'external_url': 'https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX',
                'tags': 'system design, interview prep, scalability, distributed systems, architecture',
                'duration_hours': 20,
                'total_enrollments': 500000,
                'average_rating': Decimal('4.7'),
                'what_you_learn': 'System design principles, Scalability, Load balancing, Caching, Database design, Microservices',
                'prerequisites': 'Strong programming foundation',
                'syllabus': '1. Design Principles\n2. Scalability Basics\n3. Load Balancing\n4. Caching Strategies\n5. Database Sharding\n6. Design URL Shortener\n7. Design Twitter\n8. Design Netflix\n9. Design Uber\n10. Interview Tips',
            },
            {
                'title': 'UI/UX Design Bootcamp',
                'description': 'Learn UI/UX design from scratch. Master Figma, design principles, and create beautiful user interfaces.',
                'instructor': 'Gary Simon (DesignCourse)',
                'price': Decimal('0.00'),
                'category': 'ui_ux_design',
                'difficulty': 'beginner',
                'platform': 'youtube',
                'external_url': 'https://www.youtube.com/c/DesignCourse',
                'tags': 'ui design, ux design, figma, design principles, prototyping, user experience',
                'duration_hours': 15,
                'total_enrollments': 1000000,
                'average_rating': Decimal('4.8'),
                'what_you_learn': 'Design fundamentals, Color theory, Typography, Figma, Prototyping, User research, Design systems',
                'prerequisites': 'None',
                'syllabus': '1. Design Principles\n2. Color Theory\n3. Typography\n4. Layout & Spacing\n5. Figma Basics\n6. Components\n7. Prototyping\n8. User Research\n9. Design Systems\n10. Portfolio Projects',
            },
            {
                'title': 'Unity Game Development Course',
                'description': 'Learn game development with Unity. Create 2D and 3D games using C#. Build real games from scratch.',
                'instructor': 'Brackeys',
                'price': Decimal('0.00'),
                'category': 'game_development',
                'difficulty': 'beginner',
                'platform': 'youtube',
                'external_url': 'https://www.youtube.com/c/Brackeys/playlists',
                'tags': 'unity, game development, c#, 2d games, 3d games, indie games',
                'duration_hours': 30,
                'total_enrollments': 3000000,
                'average_rating': Decimal('4.9'),
                'what_you_learn': 'Unity interface, C# programming, Physics systems, Animation, UI design, Game publishing',
                'prerequisites': 'None',
                'syllabus': '1. Unity Setup\n2. Interface Overview\n3. C# Basics\n4. Movement & Controls\n5. Physics\n6. Animation\n7. 2D Game Development\n8. 3D Game Development\n9. Audio\n10. Publishing',
            },
            {
                'title': 'TensorFlow Developer Certificate',
                'description': 'Prepare for the TensorFlow Developer Certificate exam. Master deep learning with TensorFlow through practical projects.',
                'instructor': 'Laurence Moroney (Google)',
                'price': Decimal('49.00'),
                'category': 'machine_learning',
                'difficulty': 'intermediate',
                'platform': 'coursera',
                'external_url': 'https://www.coursera.org/professional-certificates/tensorflow-in-practice',
                'tags': 'tensorflow, deep learning, machine learning, neural networks, certification, google',
                'duration_hours': 80,
                'total_enrollments': 200000,
                'average_rating': Decimal('4.7'),
                'what_you_learn': 'TensorFlow fundamentals, CNNs, NLP with TensorFlow, Time series, Sequences, TF Lite',
                'prerequisites': 'Python basics, Basic ML concepts',
                'syllabus': '1. Introduction to TensorFlow\n2. CNNs in TensorFlow\n3. NLP in TensorFlow\n4. Sequences & Prediction\n5. Exam Preparation',
            },
        ]

        created_count = 0
        updated_count = 0

        for course_data in courses_data:
            course, created = Course.objects.update_or_create(
                title=course_data['title'],
                platform=course_data['platform'],
                defaults=course_data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created: {course.title}'))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'Updated: {course.title}'))

        self.stdout.write(self.style.SUCCESS(f'\nDone! Created {created_count} courses, updated {updated_count} courses.'))
        self.stdout.write(self.style.SUCCESS(f'Total courses in database: {Course.objects.count()}'))
