# Generated by Django 4.2.27 on 2026-01-13 03:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The title of the course', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the course content and objectives')),
                ('instructor', models.CharField(help_text='Name of the course instructor', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Course price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('category', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('artificial_intelligence', 'Artificial Intelligence'), ('cloud_computing', 'Cloud Computing'), ('cybersecurity', 'Cybersecurity'), ('devops', 'DevOps'), ('blockchain', 'Blockchain'), ('game_development', 'Game Development'), ('ui_ux_design', 'UI/UX Design'), ('database', 'Database'), ('programming_languages', 'Programming Languages'), ('software_engineering', 'Software Engineering'), ('networking', 'Networking'), ('other', 'Other')], db_index=True, default='other', help_text='Primary category of the course', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', help_text='Difficulty level of the course', max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='URL to the course introduction video', max_length=500, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Course cover image', null=True, upload_to='course_covers/')),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags for better recommendations')),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Estimated course duration in hours')),
                ('total_enrollments', models.PositiveIntegerField(default=0, help_text='Total number of student enrollments')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average student rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether the course is visible to students')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'apex_courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, help_text='Student profile picture', null=True, upload_to='profile_pics/')),
                ('resume', models.FileField(blank=True, help_text='PDF resume for AI career analysis', null=True, upload_to='resumes/')),
                ('focus_points', models.PositiveIntegerField(default=0, help_text='Accumulated focus points from Focus Mode sessions')),
                ('total_focus_time_minutes', models.PositiveIntegerField(default=0, help_text='Total time spent in Focus Mode (minutes)')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('career_interests', models.TextField(blank=True, help_text="Student's career interests and goals")),
                ('preferred_difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', help_text='Preferred course difficulty level', max_length=20)),
                ('courses_completed', models.PositiveIntegerField(default=0, help_text='Number of courses completed')),
                ('total_learning_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total hours spent learning', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'apex_student_profiles',
            },
        ),
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('viewed', 'Viewed'), ('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='viewed', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Course completion percentage', validators=[django.core.validators.MaxValueValidator(100)])),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, help_text='Time spent on this course in minutes')),
                ('focus_sessions', models.PositiveIntegerField(default=0, help_text='Number of Focus Mode sessions for this course')),
                ('focus_points_earned', models.PositiveIntegerField(default=0, help_text='Focus points earned while studying this course')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Student rating for this course (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, help_text="Student's notes for this course")),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the course was completed', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_logs', to='learning.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_logs', to='learning.studentprofile')),
            ],
            options={
                'verbose_name': 'Learning Log',
                'verbose_name_plural': 'Learning Logs',
                'db_table': 'apex_learning_logs',
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Session duration in minutes')),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Points earned in this session')),
                ('total_frames_captured', models.PositiveIntegerField(default=0, help_text='Total frames analyzed')),
                ('frames_with_face_detected', models.PositiveIntegerField(default=0, help_text='Frames where face was detected')),
                ('attention_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated attention score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether session is currently active')),
                ('learning_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_focus_sessions', to='learning.learninglog')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to='learning.studentprofile')),
            ],
            options={
                'verbose_name': 'Focus Session',
                'verbose_name_plural': 'Focus Sessions',
                'db_table': 'apex_focus_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'difficulty'], name='apex_course_categor_820071_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', '-created_at'], name='apex_course_is_publ_8a43d0_idx'),
        ),
        migrations.AddIndex(
            model_name='learninglog',
            index=models.Index(fields=['student', 'status'], name='apex_learni_student_c997ba_idx'),
        ),
        migrations.AddIndex(
            model_name='learninglog',
            index=models.Index(fields=['course', '-last_accessed_at'], name='apex_learni_course__d11951_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learninglog',
            unique_together={('student', 'course')},
        ),
    ]
