# Generated by Django 4.2.27 on 2026-01-14 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', help_text='Conversation title (auto-generated from first message)', max_length=255)),
                ('ai_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq (Llama)'), ('cohere', 'Cohere')], default='gemini', help_text='AI provider used for this conversation', max_length=50)),
                ('context', models.TextField(blank=True, help_text='Additional context for the AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Whether conversation is archived')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Conversation',
                'verbose_name_plural': 'Chat Conversations',
                'db_table': 'apex_chat_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='external_url',
            field=models.URLField(blank=True, help_text='Link to the course on external platform', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='platform',
            field=models.CharField(choices=[('apex', 'Apex'), ('udemy', 'Udemy'), ('youtube', 'YouTube'), ('coursera', 'Coursera'), ('infosys', 'Infosys Springboard'), ('nptel', 'NPTEL'), ('cisco', 'Cisco Networking Academy'), ('cyfrin', 'Cyfrin Updraft'), ('freecodecamp', 'freeCodeCamp'), ('hackerrank', 'HackerRank'), ('codechef', 'CodeChef'), ('leetcode', 'LeetCode'), ('edx', 'edX'), ('mit', 'MIT OpenCourseWare')], default='apex', help_text='Platform where the course is hosted', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Prerequisites for this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Course syllabus or curriculum outline'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_learn',
            field=models.TextField(blank=True, help_text='Key learning outcomes'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_ai_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq (Llama)'), ('cohere', 'Cohere'), ('auto', 'Auto (Best Available)')], default='gemini', help_text='Preferred AI provider for chat', max_length=50)),
                ('ai_response_style', models.CharField(choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('detailed', 'Detailed')], default='balanced', help_text='Preferred AI response verbosity', max_length=50)),
                ('preferred_difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('preferred_categories', models.JSONField(blank=True, default=list, help_text='List of preferred course categories')),
                ('learning_goals', models.TextField(blank=True, help_text="User's learning goals")),
                ('current_role', models.CharField(blank=True, help_text="User's current job role", max_length=255)),
                ('target_role', models.CharField(blank=True, help_text="User's target career role", max_length=255)),
                ('skills', models.JSONField(blank=True, default=list, help_text="List of user's skills")),
                ('theme', models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode'), ('system', 'System Default')], default='dark', max_length=20)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'apex_user_preferences',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System')], default='user', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Tokens used for this message')),
                ('model_used', models.CharField(blank=True, help_text='Specific AI model used for response', max_length=100)),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='Response time in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_helpful', models.BooleanField(blank=True, help_text='User feedback on response helpfulness', null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='learning.chatconversation')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'apex_chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
