# Generated by Django 4.2.27 on 2026-01-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_chatconversation_course_external_url_course_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL to the course thumbnail image', max_length=500, null=True),
        ),
    ]
