# Generated by Django 4.2.27 on 2026-02-06 14:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0003_add_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the study room', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description or topic of the study session')),
                ('room_code', models.CharField(db_index=True, help_text='Unique room code for joining', max_length=8, unique=True)),
                ('is_private', models.BooleanField(default=False, help_text='Private rooms require room code to join')),
                ('max_participants', models.PositiveIntegerField(default=6, help_text='Maximum number of participants (2-8)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)])),
                ('category', models.CharField(choices=[('general', 'General Study'), ('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('artificial_intelligence', 'Artificial Intelligence'), ('cloud_computing', 'Cloud Computing'), ('cybersecurity', 'Cybersecurity'), ('devops', 'DevOps'), ('blockchain', 'Blockchain'), ('programming_languages', 'Programming Languages'), ('database', 'Database'), ('dsa', 'Data Structures & Algorithms'), ('interview_prep', 'Interview Preparation'), ('competitive_programming', 'Competitive Programming'), ('other', 'Other')], default='general', help_text='Study topic category', max_length=50)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('ended', 'Ended')], default='waiting', max_length=20)),
                ('pomodoro_work_minutes', models.PositiveIntegerField(default=25, help_text='Work duration in minutes')),
                ('pomodoro_break_minutes', models.PositiveIntegerField(default=5, help_text='Break duration in minutes')),
                ('pomodoro_rounds', models.PositiveIntegerField(default=4, help_text='Number of Pomodoro rounds')),
                ('timer_running', models.BooleanField(default=False, help_text='Whether the shared timer is currently running')),
                ('timer_started_at', models.DateTimeField(blank=True, help_text='When the current timer session started', null=True)),
                ('current_round', models.PositiveIntegerField(default=1, help_text='Current Pomodoro round')),
                ('is_break', models.BooleanField(default=False, help_text="Whether it's currently a break period")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(help_text='Room creator/host', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Room',
                'verbose_name_plural': 'Study Rooms',
                'db_table': 'apex_study_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Message content', max_length=1000)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('system', 'System'), ('emoji', 'Emoji Reaction')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='learning.studyroom')),
                ('sender', models.ForeignKey(blank=True, help_text='Null for system messages', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Message',
                'verbose_name_plural': 'Room Messages',
                'db_table': 'apex_room_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether user is currently in the room')),
                ('is_muted', models.BooleanField(default=False, help_text="Whether user's audio is muted")),
                ('is_camera_on', models.BooleanField(default=False, help_text="Whether user's camera is on")),
                ('focus_time_minutes', models.PositiveIntegerField(default=0, help_text='Focus time in this room session')),
                ('focus_points_earned', models.PositiveIntegerField(default=0, help_text='Focus points earned in this room')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='learning.studyroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Participant',
                'verbose_name_plural': 'Room Participants',
                'db_table': 'apex_room_participants',
                'ordering': ['joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
