# Generated by Django 4.2.27 on 2026-02-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_studyroom_roommessage_roomparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='timer_paused_remaining',
            field=models.PositiveIntegerField(blank=True, help_text='Remaining seconds when timer was paused', null=True),
        ),
    ]
