# Generated by Django 4.2.27 on 2026-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_studyroom_timer_paused_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipant',
            name='is_muted',
            field=models.BooleanField(default=True, help_text="Whether user's audio is muted"),
        ),
    ]
