# Generated by Django 4.2.27 on 2026-02-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_roomparticipant_is_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Last heartbeat from this participant'),
        ),
    ]
