# Generated by Django 4.2.27 on 2026-02-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_roomparticipant_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='peer_id',
            field=models.CharField(blank=True, default='', help_text='PeerJS peer ID for WebRTC connections', max_length=100),
        ),
    ]
